export const GET_STUDENTS_REQUEST='GET_STUDENTS_REQUEST';
export const GET_STUDENTS_SUCCESS='GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAIL='GET_STUDENTS_FAIL';
export const DELETE_STUDENT_REQUEST='DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS='DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL='DELETE_STUDENT_FAIL';